# 9.11
Given the equations
```
2x1 - 6x2 - x3 = -38
-3x1 - x2 + 7x3 = -34
-8x1 + x2 - 2x3 = -20
```

1. Solve  by  Gauss  Jordan.  Show  all  steps of the computation.
2. Substitute your results into the original equations to check your  answer

In [1]:
import numpy as np

In [2]:
def test_solution(matrix,solution):
    print("***Substitute Solution to Equation***")
    for r in range(len(matrix)):
        res = 0
        for c in range(len(matrix[0])-1):
            res += matrix[r][c]*solution[c]
        print('Result', round(res,2), 'True Value', matrix[r][-1])
        #assert res == equation_matrix_copy[r][-1]

In [3]:
def gauss_jordan(equation_matrix):
    m = len(equation_matrix)
    equation_matrix = equation_matrix*1.0 
    rows = set([row for row in range(m)])
    def helper(r):
        equation_matrix[r] = equation_matrix[r]/(equation_matrix[r][r])
        for row in rows-set([r]):
            elim_factor = equation_matrix[row][r]
            elim_equation = elim_factor*equation_matrix[r]
            equation_matrix[row] -= elim_equation

    for r in range(m):
        helper(r)

    print('Matrix after Transform')
    print(equation_matrix)
    solution = [equation_matrix[i][-1] for i in range(len(equation_matrix))]
    print('Solution:', solution)
    return solution

In [4]:
# 2. Substitute solution to check result
equation_matrix = np.array([[2,-6,-1,-38],[-3,-1,7,-34],[-8,1,-2,-20]])
equation_matrix_orig = deepcopy(equation_matrix)
print('Original Matrix')
print(equation_matrix_orig)
solution = gauss_jordan(equation_matrix)
test_solution(equation_matrix_orig, solution)

Original Matrix
[[  2  -6  -1 -38]
 [ -3  -1   7 -34]
 [ -8   1  -2 -20]]
Matrix after Transform
[[ 1.  0.  0.  4.]
 [-0.  1.  0.  8.]
 [-0. -0.  1. -2.]]
Solution: [3.9999999999999982, 8.0, -1.9999999999999993]
***Substitute Solution to Equation***
Result -38.0 True Value -38
Result -34.0 True Value -34
Result -20.0 True Value -20


In [5]:
# Test Text book Solution
equation_matrix = np.array([[3,-0.1,-0.2,7.85],[0.1,7,-0.3,-19.3],[0.3,-0.2,10,71.4]])
equation_matrix_orig = deepcopy(equation_matrix)
solution = gauss_jordan(equation_matrix)
test_solution(equation_matrix_orig, solution)

Matrix after Transform
[[ 1.   0.   0.   3. ]
 [ 0.   1.   0.  -2.5]
 [ 0.   0.   1.   7. ]]
Solution: [3.0, -2.5, 7.000000000000002]
***Substitute Solution to Equation***
Result 7.85 True Value 7.85
Result -19.3 True Value -19.3
Result 71.4 True Value 71.4


# 9.18 
Develop, debug, and test a program in either a high-level language or macro language of your choice to solve a system of equations with Gauss elimination with partial pivoting. Base the program on the pseudocode from Fig. 9.6. Test the program using the following system (which has an answer of x1 = x2 = x3 = 1)

In [6]:
equation_matrix = np.array([[1,2,-1,2],[5,2,2,9],[-3,5,-1,1]])
equation_matrix_orig = deepcopy(equation_matrix)
print('Original Matrix')
print(equation_matrix_orig)
solution = gauss_jordan(equation_matrix)
test_solution(equation_matrix_orig, solution)

Original Matrix
[[ 1  2 -1  2]
 [ 5  2  2  9]
 [-3  5 -1  1]]
Matrix after Transform
[[1. 0. 0. 1.]
 [0. 1. 0. 1.]
 [0. 0. 1. 1.]]
Solution: [1.0, 1.0, 1.0]
***Substitute Solution to Equation***
Result 2.0 True Value 2
Result 9.0 True Value 9
Result 1.0 True Value 1
